use super::*;

impl Harness {
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn initialize_global_window_entries(
        &mut self,
        css: &Value,
        decode_uri_callable: &Value,
        decode_uri_component_callable: &Value,
        create_image_bitmap_callable: &Value,
        object_constructor: &Value,
        reflect_object: &Value,
        clipboard_item_constructor: &Value,
        file_constructor: &Value,
        image_bitmap_constructor: &Value,
        storage_constructor: &Value,
        cookie_store_constructor: &Value,
        cache_storage_constructor: &Value,
        cache_constructor: &Value,
        worker_constructor: &Value,
        data_transfer_constructor: &Value,
        option_constructor: &Value,
        node_list_constructor: &Value,
        text_track_constructor: &Value,
        text_track_list_constructor: &Value,
        time_ranges_constructor: &Value,
        radio_node_list_constructor: &Value,
        html_collection_constructor: &Value,
        html_form_controls_collection_constructor: &Value,
        html_options_collection_constructor: &Value,
        text_encoder_constructor: &Value,
        text_decoder_constructor: &Value,
        text_encoder_stream_constructor: &Value,
        text_decoder_stream_constructor: &Value,
        css_style_sheet_constructor: &Value,
        keyboard_event_constructor: &Value,
        wheel_event_constructor: &Value,
        navigate_event_constructor: &Value,
        pointer_event_constructor: &Value,
        hash_change_event_constructor: &Value,
        error_event_constructor: &Value,
        before_unload_event_constructor: &Value,
        image_data_constructor: &Value,
        audio_constructor: &Value,
        html_anchor_element_constructor: &Value,
        html_area_element_constructor: &Value,
        html_body_element_constructor: &Value,
        html_br_element_constructor: &Value,
        html_base_element_constructor: &Value,
        html_audio_element_constructor: &Value,
        html_button_element_constructor: &Value,
        html_canvas_element_constructor: &Value,
        html_data_element_constructor: &Value,
        html_datalist_element_constructor: &Value,
        html_select_element_constructor: &Value,
        html_option_element_constructor: &Value,
    ) {
        let mut window_entries = self.dom_runtime.window_object.borrow_mut();
        for (name, value) in [
            ("CSS", css),
            ("decodeURI", decode_uri_callable),
            ("decodeURIComponent", decode_uri_component_callable),
            ("createImageBitmap", create_image_bitmap_callable),
            ("Object", object_constructor),
            ("Reflect", reflect_object),
            ("ClipboardItem", clipboard_item_constructor),
            ("File", file_constructor),
            ("ImageBitmap", image_bitmap_constructor),
            ("Storage", storage_constructor),
            ("CookieStore", cookie_store_constructor),
            ("CacheStorage", cache_storage_constructor),
            ("Cache", cache_constructor),
            ("Worker", worker_constructor),
            ("DataTransfer", data_transfer_constructor),
            ("Option", option_constructor),
            ("NodeList", node_list_constructor),
            ("TextTrack", text_track_constructor),
            ("TextTrackList", text_track_list_constructor),
            ("TimeRanges", time_ranges_constructor),
            ("RadioNodeList", radio_node_list_constructor),
            ("HTMLCollection", html_collection_constructor),
            (
                "HTMLFormControlsCollection",
                html_form_controls_collection_constructor,
            ),
            ("HTMLOptionsCollection", html_options_collection_constructor),
            ("TextEncoder", text_encoder_constructor),
            ("TextDecoder", text_decoder_constructor),
            ("TextEncoderStream", text_encoder_stream_constructor),
            ("TextDecoderStream", text_decoder_stream_constructor),
            ("CSSStyleSheet", css_style_sheet_constructor),
            ("KeyboardEvent", keyboard_event_constructor),
            ("WheelEvent", wheel_event_constructor),
            ("NavigateEvent", navigate_event_constructor),
            ("PointerEvent", pointer_event_constructor),
            ("HashChangeEvent", hash_change_event_constructor),
            ("ErrorEvent", error_event_constructor),
            ("BeforeUnloadEvent", before_unload_event_constructor),
            ("ImageData", image_data_constructor),
            ("Audio", audio_constructor),
            ("HTMLAnchorElement", html_anchor_element_constructor),
            ("HTMLAreaElement", html_area_element_constructor),
            ("HTMLBodyElement", html_body_element_constructor),
            ("HTMLBRElement", html_br_element_constructor),
            ("HTMLBaseElement", html_base_element_constructor),
            ("HTMLAudioElement", html_audio_element_constructor),
            ("HTMLButtonElement", html_button_element_constructor),
            ("HTMLCanvasElement", html_canvas_element_constructor),
            ("HTMLDataElement", html_data_element_constructor),
            ("HTMLDataListElement", html_datalist_element_constructor),
            ("HTMLSelectElement", html_select_element_constructor),
            ("HTMLOptionElement", html_option_element_constructor),
        ] {
            Self::object_set_entry(&mut window_entries, name.to_string(), value.clone());
        }
    }
}
