use super::*;

impl Harness {
    pub(crate) fn describe_dom_prop(&self, prop: &DomProp) -> String {
        match prop {
            DomProp::Attributes => "attributes".into(),
            DomProp::AssignedSlot => "assignedSlot".into(),
            DomProp::Value => "value".into(),
            DomProp::Files => "files".into(),
            DomProp::FilesLength => "files.length".into(),
            DomProp::ValueAsNumber => "valueAsNumber".into(),
            DomProp::ValueAsDate => "valueAsDate".into(),
            DomProp::ValueLength => "value.length".into(),
            DomProp::ValidationMessage => "validationMessage".into(),
            DomProp::Validity => "validity".into(),
            DomProp::ValidityValueMissing => "validity.valueMissing".into(),
            DomProp::ValidityTypeMismatch => "validity.typeMismatch".into(),
            DomProp::ValidityPatternMismatch => "validity.patternMismatch".into(),
            DomProp::ValidityTooLong => "validity.tooLong".into(),
            DomProp::ValidityTooShort => "validity.tooShort".into(),
            DomProp::ValidityRangeUnderflow => "validity.rangeUnderflow".into(),
            DomProp::ValidityRangeOverflow => "validity.rangeOverflow".into(),
            DomProp::ValidityStepMismatch => "validity.stepMismatch".into(),
            DomProp::ValidityBadInput => "validity.badInput".into(),
            DomProp::ValidityValid => "validity.valid".into(),
            DomProp::ValidityCustomError => "validity.customError".into(),
            DomProp::SelectionStart => "selectionStart".into(),
            DomProp::SelectionEnd => "selectionEnd".into(),
            DomProp::SelectionDirection => "selectionDirection".into(),
            DomProp::Checked => "checked".into(),
            DomProp::Indeterminate => "indeterminate".into(),
            DomProp::Open => "open".into(),
            DomProp::ReturnValue => "returnValue".into(),
            DomProp::ClosedBy => "closedBy".into(),
            DomProp::Readonly => "readonly".into(),
            DomProp::Required => "required".into(),
            DomProp::Disabled => "disabled".into(),
            DomProp::NodeType => "nodeType".into(),
            DomProp::TextContent => "textContent".into(),
            DomProp::InnerText => "innerText".into(),
            DomProp::InnerHtml => "innerHTML".into(),
            DomProp::OuterHtml => "outerHTML".into(),
            DomProp::ClassName => "className".into(),
            DomProp::ClassList => "classList".into(),
            DomProp::ClassListLength => "classList.length".into(),
            DomProp::Part => "part".into(),
            DomProp::PartLength => "part.length".into(),
            DomProp::Id => "id".into(),
            DomProp::TagName => "tagName".into(),
            DomProp::LocalName => "localName".into(),
            DomProp::NamespaceUri => "namespaceURI".into(),
            DomProp::Prefix => "prefix".into(),
            DomProp::NextElementSibling => "nextElementSibling".into(),
            DomProp::PreviousElementSibling => "previousElementSibling".into(),
            DomProp::Slot => "slot".into(),
            DomProp::Role => "role".into(),
            DomProp::ElementTiming => "elementTiming".into(),
            DomProp::HtmlFor => "htmlFor".into(),
            DomProp::Name => "name".into(),
            DomProp::Action => "action".into(),
            DomProp::FormAction => "formAction".into(),
            DomProp::Lang => "lang".into(),
            DomProp::Dir => "dir".into(),
            DomProp::AccessKey => "accessKey".into(),
            DomProp::AutoComplete => "autocomplete".into(),
            DomProp::AutoCapitalize => "autocapitalize".into(),
            DomProp::AutoCorrect => "autocorrect".into(),
            DomProp::ContentEditable => "contentEditable".into(),
            DomProp::Draggable => "draggable".into(),
            DomProp::EnterKeyHint => "enterKeyHint".into(),
            DomProp::Inert => "inert".into(),
            DomProp::InputMode => "inputMode".into(),
            DomProp::Nonce => "nonce".into(),
            DomProp::Popover => "popover".into(),
            DomProp::Spellcheck => "spellcheck".into(),
            DomProp::TabIndex => "tabIndex".into(),
            DomProp::Translate => "translate".into(),
            DomProp::Cite => "cite".into(),
            DomProp::DateTime => "dateTime".into(),
            DomProp::BrClear => "clear".into(),
            DomProp::CaptionAlign => "align".into(),
            DomProp::ColSpan => "span".into(),
            DomProp::TableCellColSpan => "colSpan".into(),
            DomProp::RowSpan => "rowSpan".into(),
            DomProp::CanvasWidth => "width".into(),
            DomProp::CanvasHeight => "height".into(),
            DomProp::NodeEventHandler(event_name) => event_name.clone(),
            DomProp::BodyDeprecatedAttr(attr_name) => attr_name.clone(),
            DomProp::ClientWidth => "clientWidth".into(),
            DomProp::ClientHeight => "clientHeight".into(),
            DomProp::ClientLeft => "clientLeft".into(),
            DomProp::ClientTop => "clientTop".into(),
            DomProp::CurrentCssZoom => "currentCSSZoom".into(),
            DomProp::OffsetWidth => "offsetWidth".into(),
            DomProp::OffsetHeight => "offsetHeight".into(),
            DomProp::OffsetLeft => "offsetLeft".into(),
            DomProp::OffsetTop => "offsetTop".into(),
            DomProp::ScrollWidth => "scrollWidth".into(),
            DomProp::ScrollHeight => "scrollHeight".into(),
            DomProp::ScrollLeft => "scrollLeft".into(),
            DomProp::ScrollTop => "scrollTop".into(),
            DomProp::ScrollLeftMax => "scrollLeftMax".into(),
            DomProp::ScrollTopMax => "scrollTopMax".into(),
            DomProp::ShadowRoot => "shadowRoot".into(),
            DomProp::Dataset(_) => "dataset".into(),
            DomProp::Style(_) => "style".into(),
            DomProp::AriaString(prop_name) => prop_name.clone(),
            DomProp::AriaElementRefSingle(prop_name) => prop_name.clone(),
            DomProp::AriaElementRefList(prop_name) => prop_name.clone(),
            DomProp::ActiveElement => "activeElement".into(),
            DomProp::ActiveViewTransition => "activeViewTransition".into(),
            DomProp::AdoptedStyleSheets => "adoptedStyleSheets".into(),
            DomProp::AdoptedStyleSheetsLength => "adoptedStyleSheets.length".into(),
            DomProp::CharacterSet => "characterSet".into(),
            DomProp::CompatMode => "compatMode".into(),
            DomProp::ContentType => "contentType".into(),
            DomProp::ReadyState => "readyState".into(),
            DomProp::Referrer => "referrer".into(),
            DomProp::Title => "title".into(),
            DomProp::BaseUri => "baseURI".into(),
            DomProp::AudioSrc => "src".into(),
            DomProp::AudioAutoplay => "autoplay".into(),
            DomProp::AudioControls => "controls".into(),
            DomProp::AudioControlsList => "controlsList".into(),
            DomProp::AudioCrossOrigin => "crossOrigin".into(),
            DomProp::AudioDisableRemotePlayback => "disableRemotePlayback".into(),
            DomProp::AudioLoop => "loop".into(),
            DomProp::AudioMuted => "muted".into(),
            DomProp::AudioPreload => "preload".into(),
            DomProp::VideoDisablePictureInPicture => "disablePictureInPicture".into(),
            DomProp::VideoPlaysInline => "playsInline".into(),
            DomProp::VideoPoster => "poster".into(),
            DomProp::Url => "URL".into(),
            DomProp::DocumentUri => "documentURI".into(),
            DomProp::Location => "location".into(),
            DomProp::LocationHref => "location.href".into(),
            DomProp::LocationProtocol => "location.protocol".into(),
            DomProp::LocationHost => "location.host".into(),
            DomProp::LocationHostname => "location.hostname".into(),
            DomProp::LocationPort => "location.port".into(),
            DomProp::LocationPathname => "location.pathname".into(),
            DomProp::LocationSearch => "location.search".into(),
            DomProp::LocationHash => "location.hash".into(),
            DomProp::LocationOrigin => "location.origin".into(),
            DomProp::LocationAncestorOrigins => "location.ancestorOrigins".into(),
            DomProp::History => "history".into(),
            DomProp::HistoryLength => "history.length".into(),
            DomProp::HistoryState => "history.state".into(),
            DomProp::HistoryScrollRestoration => "history.scrollRestoration".into(),
            DomProp::DefaultView => "defaultView".into(),
            DomProp::Hidden => "hidden".into(),
            DomProp::VisibilityState => "visibilityState".into(),
            DomProp::Forms => "forms".into(),
            DomProp::Images => "images".into(),
            DomProp::Links => "links".into(),
            DomProp::Scripts => "scripts".into(),
            DomProp::Children => "children".into(),
            DomProp::ChildElementCount => "childElementCount".into(),
            DomProp::FirstElementChild => "firstElementChild".into(),
            DomProp::LastElementChild => "lastElementChild".into(),
            DomProp::CurrentScript => "currentScript".into(),
            DomProp::FormsLength => "forms.length".into(),
            DomProp::ImagesLength => "images.length".into(),
            DomProp::LinksLength => "links.length".into(),
            DomProp::ScriptsLength => "scripts.length".into(),
            DomProp::ChildrenLength => "children.length".into(),
            DomProp::AnchorAlt => "alt".into(),
            DomProp::AnchorAttributionSrc => "attributionSrc".into(),
            DomProp::AnchorDownload => "download".into(),
            DomProp::AnchorHash => "hash".into(),
            DomProp::AnchorHost => "host".into(),
            DomProp::AnchorHostname => "hostname".into(),
            DomProp::AnchorHref => "href".into(),
            DomProp::AnchorHreflang => "hreflang".into(),
            DomProp::AnchorInterestForElement => "interestForElement".into(),
            DomProp::AnchorOrigin => "origin".into(),
            DomProp::AnchorPassword => "password".into(),
            DomProp::AnchorPathname => "pathname".into(),
            DomProp::AnchorPing => "ping".into(),
            DomProp::AnchorPort => "port".into(),
            DomProp::AnchorProtocol => "protocol".into(),
            DomProp::AnchorReferrerPolicy => "referrerPolicy".into(),
            DomProp::AnchorRel => "rel".into(),
            DomProp::AnchorRelList => "relList".into(),
            DomProp::AnchorRelListLength => "relList.length".into(),
            DomProp::AnchorSearch => "search".into(),
            DomProp::AnchorTarget => "target".into(),
            DomProp::AnchorText => "text".into(),
            DomProp::AnchorType => "type".into(),
            DomProp::AnchorUsername => "username".into(),
            DomProp::AnchorNoHref => "noHref".into(),
            DomProp::AnchorCharset => "charset".into(),
            DomProp::AnchorCoords => "coords".into(),
            DomProp::AnchorRev => "rev".into(),
            DomProp::AnchorShape => "shape".into(),
            DomProp::Data => "data".into(),
            DomProp::SrcDoc => "srcdoc".into(),
            DomProp::UseMap => "useMap".into(),
            DomProp::Size => "size".into(),
            DomProp::Min => "min".into(),
            DomProp::Max => "max".into(),
            DomProp::Step => "step".into(),
            DomProp::MaxLength => "maxLength".into(),
            DomProp::MinLength => "minLength".into(),
            DomProp::Rows => "rows".into(),
            DomProp::Cols => "cols".into(),
        }
    }

    pub(crate) fn event_node_label(&self, node: NodeId) -> String {
        if node.0 >= self.dom.nodes.len() {
            return format!("event-target-{}", node.0);
        }
        if let Some(id) = self.dom.attr(node, "id") {
            if !id.is_empty() {
                return id;
            }
        }
        self.dom
            .tag_name(node)
            .map(ToOwned::to_owned)
            .unwrap_or_else(|| format!("node-{}", node.0))
    }

    pub(crate) fn trace_node_label(&self, node: NodeId) -> String {
        if node.0 >= self.dom.nodes.len() {
            return format!("event-target-{}", node.0);
        }
        if let Some(id) = self.dom.attr(node, "id") {
            if !id.is_empty() {
                return format!("#{id}");
            }
        }
        self.dom
            .tag_name(node)
            .map(ToOwned::to_owned)
            .unwrap_or_else(|| format!("node-{}", node.0))
    }
}
